# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

d_mixlink_binom <- function(y, m, mean, Pi, kappa, subdiv, rel_tol, abs_tol) {
    .Call(mixlink_d_mixlink_binom, y, m, mean, Pi, kappa, subdiv, rel_tol, abs_tol)
}

d_mixlink_pois <- function(y, mean, Pi, kappa) {
    .Call(mixlink_d_mixlink_pois, y, mean, Pi, kappa)
}

find_vertices_prob <- function(p, Pi, tol) {
    .Call(mixlink_find_vertices_prob, p, Pi, tol)
}

find_vertices_nonneg <- function(p, Pi) {
    .Call(mixlink_find_vertices_nonneg, p, Pi)
}

mixlink_gibbs_Q_binom <- function(y, m, mean, psi, Pi, kappa, find_vert_tol) {
    .Call(mixlink_mixlink_gibbs_Q_binom, y, m, mean, psi, Pi, kappa, find_vert_tol)
}

mixlink_gibbs_Q_pois <- function(y, mean, psi, Pi, kappa) {
    .Call(mixlink_mixlink_gibbs_Q_pois, y, mean, psi, Pi, kappa)
}

hyperg_1F1 <- function(a, b, x) {
    .Call(mixlink_hyperg_1F1, a, b, x)
}

rwmetrop_cpp <- function(par_init, logf, pr_var_half_trans, grp_idx_list, R, burn, thin, report_period) {
    .Call(mixlink_rwmetrop_cpp, par_init, logf, pr_var_half_trans, grp_idx_list, R, burn, thin, report_period)
}

seq_int_ordered <- function(from, to) {
    .Call(mixlink_seq_int_ordered, from, to)
}

